package sysx

import (
	"context"
	"encoding/binary"
	"fmt"
	"net"
	"path/filepath"
	"strings"

	"github.com/quinlan102/homeport/internal/model"
)

// The feed-driven blocklist.
// -------------------------
// A drop list in front of every TCP port, fed by a threat feed the frontend
// refreshes on a timer rather than by anything an operator typed.
//
// It is a table of its own, and that is the load-bearing decision here rather
// than tidiness. BuildProtectRuleset renders `delete table` followed by the
// whole table, so every change to protection rebuilds it - which is why
// Engine.protectApplied exists at all, to keep a save that touched nothing
// from resetting every counter, unparking every blocked source and releasing
// every engaged region lock. A list that refreshes several times a day cannot
// live inside a table with that property: it would hand a flood a clean slate
// on its own schedule, with nothing connecting the two. Here the refresh
// touches one set and no rule, in a single nft transaction, so the counters
// and everything failover_protect holds are untouched by it.
//
// Being its own table also means it works with protection switched off
// entirely, which is the ordinary case for a site that wants a blocklist and
// no rate limiting, and it keeps nft_test's assertion about the published
// table literally true.

// NFTBlocklistTable is the frontend's feed-driven drop table.
const NFTBlocklistTable = "failover_blocklist"

// CounterBlocklist names the drop rule's counter, which is what tells an
// operator whether the list is doing anything at all.
const CounterBlocklist = "blocklist"

// The two sets. feed is what the refresher writes; allow is the operator's
// exceptions, consulted first.
const (
	BlocklistFeedSet  = "feed"
	BlocklistAllowSet = "allow"
)

// blocklistPriority puts the chain in prerouting ahead of failover_protect's
// raw chain (-300), so a listed source costs one set lookup and nothing else:
// no conntrack entry, no limiter state, no region set walk. Both are well
// ahead of dstnat (-100), where the published services are translated.
const blocklistPriority = -310

// BlocklistSpec is what the table is generated from. Deliberately not the
// networks themselves: those arrive from a third party on a timer and go into
// the set separately, which is the whole reason this table exists.
type BlocklistSpec struct {
	Enabled     bool
	PublicIface string
	// Exceptions are never dropped, whatever the feed says.
	Exceptions []string
}

// BuildBlocklistRuleset renders the table, or "" where there is nothing to
// install - the feature off, or no public interface to scope it to.
//
// The interface scoping is the same safety property the protection table
// carries and for the same reason: probes and the control channel arrive on
// tunnels, and a rule that could match them would let a third party's list
// condemn a healthy link and move traffic to a metered one. web.validate
// refuses to enable this without an interface, so reaching the empty return
// that way means a stored blob rather than a save.
func BuildBlocklistRuleset(spec BlocklistSpec) string {
	iface := strings.TrimSpace(spec.PublicIface)
	if !spec.Enabled || iface == "" {
		return ""
	}
	// Re-parsed here rather than trusted, exactly as EgressNetworks is, and
	// merged because nft rejects a whole table over one contained duplicate.
	// The operator's own list has been through validate, but this generator
	// is the boundary and a stored blob predating a rule is the case that
	// walks through one.
	allow := mergeCIDRs(EgressNetworks(spec.Exceptions))

	var b strings.Builder
	b.WriteString("# generated by failover-frontend - do not edit by hand\n")
	b.WriteString("# a drop list in front of every TCP port, from a threat feed this\n")
	b.WriteString("# host refreshes on a timer. the elements of the feed set are loaded\n")
	b.WriteString("# separately (see blocklist-feed.nft) so a refresh touches no rule\n")
	b.WriteString("# and resets no counter. scoped to the public interface, so probes,\n")
	b.WriteString("# the control channel and overlay traffic are out of reach of it.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTBlocklistTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTBlocklistTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTBlocklistTable)

	// The feed set is declared empty and filled by ApplyBlocklistElements.
	// Not `dynamic`: nothing in the packet path ever writes to it, only the
	// control plane does, so it needs neither the flag nor a size - and a
	// size would be a ceiling on a list whose length is somebody else's
	// decision.
	fmt.Fprintf(&b, "\tset %s {\n", BlocklistFeedSet)
	b.WriteString("\t\ttype ipv4_addr\n")
	b.WriteString("\t\tflags interval\n")
	b.WriteString("\t\tcomment \"networks from the threat feed; loaded by the agent, not from the packet path\"\n")
	b.WriteString("\t}\n\n")

	if len(allow) > 0 {
		fmt.Fprintf(&b, "\tset %s {\n", BlocklistAllowSet)
		b.WriteString("\t\ttype ipv4_addr\n")
		b.WriteString("\t\tflags interval\n")
		b.WriteString("\t\tcomment \"networks the operator has exempted from the feed\"\n")
		fmt.Fprintf(&b, "\t\telements = { %s }\n", geoElements(allow))
		b.WriteString("\t}\n\n")
	}

	b.WriteString("\tchain raw {\n")
	fmt.Fprintf(&b, "\t\ttype filter hook prerouting priority %d; policy accept;\n", blocklistPriority)
	fmt.Fprintf(&b, "\t\tiifname != %q accept\n", nftSafe(iface))
	if len(allow) > 0 {
		b.WriteString("\t\t# The operator's exceptions, ahead of the feed: the feed is the one\n")
		b.WriteString("\t\t# list here nobody in this deployment reviewed, and a false positive\n")
		b.WriteString("\t\t# in it is a visitor who cannot connect with nothing saying why.\n")
		fmt.Fprintf(&b, "\t\tip saddr @%s accept\n", BlocklistAllowSet)
	}
	b.WriteString("\t\t# TCP only, deliberately. A false positive on a UDP game port would\n")
	b.WriteString("\t\t# drop a player mid-match; on TCP it is a connection that does not\n")
	b.WriteString("\t\t# open, which is the recoverable direction. Stateless and on every\n")
	b.WriteString("\t\t# packet, like the region locks: the set answer is fixed per address,\n")
	b.WriteString("\t\t# so a source the list admits can never be newly caught, a listed\n")
	b.WriteString("\t\t# flood costs no conntrack entry, and a source appearing in the feed\n")
	b.WriteString("\t\t# also ends flows already in progress.\n")
	fmt.Fprintf(&b, "\t\tmeta l4proto tcp ip saddr @%s counter drop comment %q\n",
		BlocklistFeedSet, CounterBlocklist)
	b.WriteString("\t}\n")

	b.WriteString("}\n")
	return b.String()
}

// BuildBlocklistElements renders the set contents as one nft transaction: a
// flush and an add, which the kernel applies atomically, so there is no
// instant at which the list is half replaced.
//
// It returns "" when nothing survives the parse, and the caller must read
// that as "nothing to load" rather than as "empty the set". That is the safe
// direction and it is chosen: a feed that came back as something this
// generator cannot use is a fault, not an instruction, and the previous list
// is better than none. Emptying the set deliberately is what rebuilding the
// table does.
func BuildBlocklistElements(networks []string) string {
	// The same treatment the operator's own lists get, for a list that has
	// had far less scrutiny: every element re-parsed and re-rendered, so no
	// unexamined byte from a third party's file reaches something nft loads
	// as root, and merged because the feed aggregates several sources whose
	// networks routinely nest - one contained duplicate and nft refuses the
	// whole transaction.
	elems := mergeCIDRs(dropNonInternet(EgressNetworks(networks)))
	if len(elems) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# generated by failover-frontend - do not edit by hand\n")
	b.WriteString("# the threat feed's networks. flush and add in one transaction, so\n")
	b.WriteString("# the set is never half replaced and no rule or counter is touched.\n\n")
	fmt.Fprintf(&b, "flush set ip %s %s\n", NFTBlocklistTable, BlocklistFeedSet)
	fmt.Fprintf(&b, "add element ip %s %s {\n\t\t\t%s\n}\n",
		NFTBlocklistTable, BlocklistFeedSet, geoElements(elems))
	return b.String()
}

// CountBlocklistElements reports how many networks BuildBlocklistElements
// would really load, which is not len(networks): the parse drops what nft
// cannot use and the merge collapses what nests. The portal reports the
// loaded figure, so it has to come from the same arithmetic.
func CountBlocklistElements(networks []string) int {
	return len(mergeCIDRs(dropNonInternet(EgressNetworks(networks))))
}

// BlocklistMinPrefix and BlocklistMaxCoverage bound what a feed can take
// off the air. The parse and the shrink guard both count entries, and
// neither says anything about how much address space an entry covers: nine
// syntactically perfect lines (1.0.0.0/8, 32.0.0.0/3, 128.0.0.0/3 and their
// like) cover half the routable internet, pass whole-or-nothing, and are
// nine entries against thousands. A poisoned CDN response or an upstream
// aggregation bug is enough to produce them, and what they drop is every
// TCP connection to every published port from half the world.
//
// The floor is applied to what would be loaded, after dropNonInternet, and
// that ordering is load-bearing: the honest level1 feed carries
// 224.0.0.0/4 and 240.0.0.0/4 from its bogon source, both shorter than /8
// and both stripped as reserved space, so a floor applied to the raw list
// would refuse the real feed every day. No allocated /7 or shorter exists
// to be listed, so a survivor shorter than /8 is never honest.
//
// The ceiling is on the merged address count. level1 after the reserved
// strip is a few tens of millions of addresses at most (Spamhaus DROP is a
// few hundred /16 to /22 networks, dshield twenty /24s, and the bogon list
// is mostly the reserved space that has already been removed), so 2^27,
// about three percent of IPv4, is several times the honest figure while
// staying far below anything that would take a meaningful share of players
// off the air.
const (
	BlocklistMinPrefix   = 8
	BlocklistMaxCoverage = uint64(1) << 27
)

// CheckBlocklist applies the prefix floor and the coverage ceiling to what
// BuildBlocklistElements would load from networks, and reports the loaded
// count on success. The count is the same arithmetic CountBlocklistElements
// does, handed back so a caller does not merge two hundred thousand entries
// twice.
func CheckBlocklist(networks []string) (int, error) {
	elems := mergeCIDRs(dropNonInternet(EgressNetworks(networks)))
	var covered uint64
	for _, c := range elems {
		_, n, err := net.ParseCIDR(c)
		if err != nil {
			continue // mergeCIDRs only emits what parsed
		}
		ones, bits := n.Mask.Size()
		if ones < BlocklistMinPrefix {
			return 0, fmt.Errorf("network %s is shorter than /%d; no honest feed lists a block that size",
				c, BlocklistMinPrefix)
		}
		covered += uint64(1) << uint(bits-ones)
	}
	if covered > BlocklistMaxCoverage {
		return 0, fmt.Errorf("the list covers %d addresses, more than the %d this is willing to drop from",
			covered, BlocklistMaxCoverage)
	}
	return len(elems), nil
}

// dropNonInternet removes feed entries that overlap space no legitimate
// source on the public interface can hold: private, carrier-grade NAT,
// loopback, link-local, "this network", multicast and the reserved block
// above it - nonInternetDestinations, the same list the egress mark is
// limited to.
//
// Two of those matter and the rest are hygiene. The aggregate feeds include a
// bogon list, so private and reserved space arrives in the ordinary case, and
// a source in it reaching the public interface is already the spoofed traffic
// Protect.DropSpoofed exists for - a second rule dropping it buys nothing and
// makes the counter mean two things. Carrier-grade NAT is the one that would
// really hurt: a feed that ever listed a slice of 100.64/10 would drop a large
// number of real mobile players at once, and every one of them would present
// as the service being down with nothing on this host naming the cause.
//
// Overlap rather than containment, because the damage is done by any entry
// that reaches into one of these ranges, whether or not it sits inside one.
func dropNonInternet(cidrs []string) []string {
	type span struct{ lo, hi uint32 }
	bounds := func(c string) (span, bool) {
		_, n, err := net.ParseCIDR(strings.TrimSpace(c))
		if err != nil || n.IP.To4() == nil {
			return span{}, false
		}
		ones, bits := n.Mask.Size()
		if bits != 32 {
			return span{}, false
		}
		lo := binary.BigEndian.Uint32(n.IP.To4())
		return span{lo, lo | (0xffffffff >> ones)}, true
	}
	var bad []span
	for _, c := range nonInternetDestinations {
		if sp, ok := bounds(c); ok {
			bad = append(bad, sp)
		}
	}
	out := make([]string, 0, len(cidrs))
	for _, c := range cidrs {
		sp, ok := bounds(c)
		if !ok {
			continue
		}
		overlaps := false
		for _, b := range bad {
			if sp.lo <= b.hi && b.lo <= sp.hi {
				overlaps = true
				break
			}
		}
		if !overlaps {
			out = append(out, c)
		}
	}
	return out
}

// ApplyBlocklistRuleset writes and loads the table.
func ApplyBlocklistRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "blocklist.nft"), ruleset)
}

// ApplyBlocklistElements writes and loads the set contents. Kept in a file of
// its own beside the table's, so what is on disk stays a readable record of
// what is in the kernel - and so a reader can tell the rules, which change
// when the operator saves, from the list, which changes on a timer.
func ApplyBlocklistElements(ctx context.Context, r Runner, stateDir, elements string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "blocklist-feed.nft"), elements)
}

// RemoveBlocklistRuleset deletes the table.
func RemoveBlocklistRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTBlocklistTable)
}

// BlocklistState reads the drop rule's counter back out of the kernel.
//
// Terse (-t), which omits set contents, and that is not a micro-optimisation:
// the feed set is thousands of interval elements and this runs on the engine's
// own goroutine every few seconds, in front of probe results and the decision
// loop. The elements are never read back at all - the agent loaded them and
// knows what it loaded, so asking nft to serialise them into JSON and
// unmarshalling them again would buy a number the caller already has.
//
// An error means the table is not there to read, which is the caller's cue to
// stop believing its own record of what is loaded.
func BlocklistState(ctx context.Context, r Runner) (model.ProtectCounter, error) {
	out, err := r.Run(ctx, "nft", "-j", "-t", "list", "table", "ip", NFTBlocklistTable)
	if err != nil {
		return model.ProtectCounter{}, err
	}
	counters, _, err := parseProtectCounters(out)
	if err != nil {
		return model.ProtectCounter{}, err
	}
	for _, c := range counters {
		if c.Name == CounterBlocklist {
			return c, nil
		}
	}
	// The table is loaded and the rule has counted nothing yet, which is the
	// ordinary state of a working blocklist on a quiet day.
	return model.ProtectCounter{Name: CounterBlocklist, Drops: true}, nil
}
