package sysx

import (
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"

	"github.com/quinlan102/homeport/internal/model"
)

// NFTTable is the dedicated table the agent owns. Nothing else is touched, so
// removing every trace of this program is one command:
//
//	nft delete table ip failover
const NFTTable = "failover"

// NFTReturnTable is the backend's table. It carries no NAT of its own - only
// the connection marking that lets reply traffic find its way back out the
// tunnel it arrived on.
const NFTReturnTable = "failover_return"

// NFTEgressTable is the frontend's optional source-NAT table.
//
// It is a table of its own rather than a chain in NFTTable, and that separation
// is the point. NFTTable carries the published services and must never contain
// a masquerade - rewriting the source there would take the real client IP away
// from srcds and the web server, which is the reason the whole system routes
// instead of proxying, and `nft_test.go` asserts it. This table rewrites the
// source of traffic travelling the other way: connections the *backend*
// originates, where there is no client address to preserve because there is no
// client. Keeping them apart means the assertion on the published ruleset stays
// literally true, and this table can be added and removed on its own.
const NFTEgressTable = "failover_egress"

// ReturnMark stamps connections that arrived through a tunnel.
//
// The backend already routes replies by source address (ip rule from the
// overlay address), which is enough while the service listens on the host. It
// stops working the moment anything DNATs further - a container on a bridge
// network being the ordinary case - because the routing decision for the reply
// happens *before* its source is rewritten back to the overlay address. At that
// moment the packet still carries the container's address, matches no rule, and
// leaves by the default route instead of the tunnel.
//
// Marking the connection on the way in and restoring that mark on the way out
// routes by connection rather than by address, which survives any number of
// translations. 0x200 is clear of the path marks (0x101-0x103) and the control
// mark (0x100).
const ReturnMark = 0x200

// BuildRuleset renders the DNAT ruleset for the published services.
//
// Destination NAT only. There is deliberately no masquerade rule: leaving the
// source address alone is what makes the backend see the real client IP, for
// UDP as well as TCP, without any proxy in the path.
func BuildRuleset(cfg model.Config) string {
	var b strings.Builder
	b.WriteString("# generated by failover-frontend - do not edit by hand\n")
	b.WriteString("# destination NAT only; source addresses are never rewritten,\n")
	b.WriteString("# so srcds and the web server see real client IPs.\n\n")

	// Atomic replace: create-if-missing, delete, redefine.
	fmt.Fprintf(&b, "table ip %s\n", NFTTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTTable)
	b.WriteString("\tchain prerouting {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")

	for _, s := range cfg.Services {
		if !s.Enabled {
			continue
		}
		proto := strings.ToLower(s.Proto)
		if proto != "tcp" && proto != "udp" {
			continue
		}
		port := fmt.Sprintf("%d", s.Port)
		if s.PortEnd > s.Port {
			port = fmt.Sprintf("%d-%d", s.Port, s.PortEnd)
		}
		var rule strings.Builder
		rule.WriteString("\t\t")
		if cfg.Frontend.PublicIface != "" {
			fmt.Fprintf(&rule, "iifname %q ", cfg.Frontend.PublicIface)
		}
		if cfg.Frontend.PublicIP != "" {
			fmt.Fprintf(&rule, "ip daddr %s ", cfg.Frontend.PublicIP)
		}
		// Almost always the backend. A service names a different overlay
		// address only where a linker agent publishes it from another host,
		// and the routing to get there is the same route widened by one
		// prefix - there is no second mechanism here.
		fmt.Fprintf(&rule, "%s dport %s dnat to %s comment %q\n",
			proto, port, s.TargetOr(cfg.Overlay.BackendIP), s.Name)
		b.WriteString(rule.String())
	}

	b.WriteString("\t}\n")
	writeMSSClamp(&b, pathIfaces(cfg))
	b.WriteString("}\n")
	return b.String()
}

func pathIfaces(cfg model.Config) []string {
	ifaces := make([]string, 0, len(cfg.Paths))
	for _, p := range cfg.Paths {
		ifaces = append(ifaces, p.Iface)
	}
	return ifaces
}

// writeMSSClamp renders a forward chain that caps the TCP MSS of every SYN
// leaving by a tunnel to what the tunnel can carry.
//
// The tunnels run at WireGuard's 1420, and everything either side of them is
// 1500. A forwarded TCP connection - a player to a containerised server, a
// container to the internet - therefore depends on path MTU discovery: the
// host in front of the tunnel sends ICMP "fragmentation needed" to whichever
// end is sending 1460-byte segments, and that end is supposed to shrink them.
// Plenty of ends never see the ICMP, because something on their side drops
// it, and Valve's are the canonical example. The handshake completes, the
// first full-size segment from the server is dropped at the tunnel, and the
// connection sits there retransmitting it: steamcmd "Connecting anonymously
// to Steam Public... Retrying..." forever, from a container routed out
// through the frontend, while the same container had no trouble by the
// house's 1500-byte path.
//
// Rewriting the MSS on the SYN tells the far end the right size up front,
// which needs no ICMP and no cooperation. `rt mtu` is the MTU of the route
// the packet is leaving by, so the value tracks the tunnel's MTU rather than
// a number written here. Forwarded packets only: a connection this host
// originates on its own address already sizes itself from the route. Only
// where there are tunnels to leave by, which is every site.
func writeMSSClamp(b *strings.Builder, ifaces []string) {
	if len(ifaces) == 0 {
		return
	}
	quoted := make([]string, 0, len(ifaces))
	for _, i := range ifaces {
		quoted = append(quoted, fmt.Sprintf("%q", i))
	}
	b.WriteString("\tchain forward {\n")
	b.WriteString("\t\ttype filter hook forward priority mangle; policy accept;\n")
	fmt.Fprintf(b, "\t\toifname { %s } tcp flags syn tcp option maxseg size set rt mtu\n",
		strings.Join(quoted, ", "))
	b.WriteString("\t}\n")
}

// BuildEgressRuleset renders the frontend's source-NAT for backend-originated
// traffic, or "" when the feature is off.
//
// The match is narrow on purpose: the overlay source address, and the public
// interface as the way out. Only the backend can send from the overlay address,
// and restricting the output interface keeps it away from anything heading back
// down a tunnel - masquerading there would rewrite the source of a reply to a
// player, which is exactly what the rest of the design exists to avoid.
//
// A configured public IP produces an snat rather than a masquerade: it is one
// less address lookup per connection, and it fails visibly if the address is
// wrong instead of silently picking a different one.
func BuildEgressRuleset(cfg model.Config) string {
	if !cfg.Frontend.BackendEgress || cfg.Overlay.BackendIP == "" || cfg.Frontend.PublicIface == "" {
		return ""
	}
	var b strings.Builder
	b.WriteString("# generated by failover-frontend - do not edit by hand\n")
	b.WriteString("# gives traffic the backend originates the frontend's public\n")
	b.WriteString("# address, so a game server is listed at the published address\n")
	b.WriteString("# rather than at the house's own internet service.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTEgressTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTEgressTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTEgressTable)
	b.WriteString("\tchain postrouting {\n")
	b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")

	// The whole overlay range, so a linker's traffic is translated by the same
	// rule as the backend's. On a site with no linkers MatchPrefix is the
	// backend's own address and this renders exactly as it always did.
	fmt.Fprintf(&b, "\t\tip saddr %s oifname %q ", cfg.Overlay.MatchPrefix(), cfg.Frontend.PublicIface)
	if cfg.Frontend.PublicIP != "" {
		fmt.Fprintf(&b, "snat to %s\n", cfg.Frontend.PublicIP)
	} else {
		b.WriteString("masquerade\n")
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// ApplyEgressRuleset loads the frontend's source-NAT table.
func ApplyEgressRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "egress.nft"), ruleset)
}

// RemoveEgressRuleset deletes the frontend's source-NAT table.
func RemoveEgressRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTEgressTable)
}

// EgressMark stamps traffic being pulled onto the tunnel from a backend-side
// network. Clear of the path marks (0x101-0x103), the control mark (0x100) and
// the return mark (0x200).
const EgressMark = 0x300

// nonInternetDestinations is every IPv4 range that cannot be reached through
// the frontend's public address: private, carrier-grade NAT, loopback,
// link-local, "this network", and multicast plus the reserved block above it.
//
// The egress mark is limited to destinations outside these, and that limit
// is the difference between the feature working and a network going dark.
// Matching on source alone stamped *everything* a container sent, and a
// container sends plenty that is not bound for the internet: its DNS queries
// to the LAN resolver, its traffic to the host's own LAN address, to a
// database on another bridge, to the panel that manages it. Every one of
// those was sent down the tunnel to a frontend that could do nothing with a
// private destination, and the symptom was a container that could not
// resolve a name or reach its own panel the moment its network was ticked.
// The frontend's NAT is an internet address; only internet traffic should
// seek it out.
var nonInternetDestinations = []string{
	"0.0.0.0/8",
	"10.0.0.0/8",
	"100.64.0.0/10",
	"127.0.0.0/8",
	"169.254.0.0/16",
	"172.16.0.0/12",
	"192.168.0.0/16",
	"224.0.0.0/3",
}

// internetOnly is the destination match that keeps the egress mark off
// traffic the frontend could not carry.
var internetOnly = "ip daddr != { " + strings.Join(nonInternetDestinations, ", ") + " }"

// BuildBackendEgressRuleset renders the backend half of the egress feature, or
// "" when no source networks are configured.
//
// Two rules, doing two different jobs:
//
// The prerouting mark is what redirects the traffic. A container's packets
// arrive at the host over its bridge and are forwarded, so the routing decision
// for them happens after this hook - setting the mark here is what makes
// `ip rule fwmark 0x300 lookup 100` send them down the active tunnel instead of
// out to pfSense. Table 100 is the return table, which already tracks the
// frontend's choice, so this follows failover with nothing extra to maintain.
// Only internet destinations are marked - see nonInternetDestinations for why
// the LAN, the other bridges and the resolver have to keep their normal route.
//
// The postrouting SNAT rewrites the source to the overlay address, because that
// is what the frontend's own egress rule matches and what it can route a reply
// back to. Without it the packet arrives at the frontend carrying a private
// container address that nothing downstream knows how to answer.
//
// The SNAT priority is deliberately ahead of srcnat (100), which is where
// Docker installs its own masquerade. Left to run first, Docker would rewrite
// the source to an address on the output interface - and the tunnels carry no
// address at all, because wg-quick runs with Table = off and no Address.
func BuildBackendEgressRuleset(cidrs, ifaces []string, overlayIP string) string {
	cidrs = EgressNetworks(cidrs)
	overlayIP = AddressLiteral(overlayIP)
	if len(cidrs) == 0 || len(ifaces) == 0 || overlayIP == "" {
		return ""
	}
	set := func(items []string) string {
		quoted := make([]string, 0, len(items))
		for _, i := range items {
			quoted = append(quoted, fmt.Sprintf("%q", i))
		}
		return "{ " + strings.Join(quoted, ", ") + " }"
	}

	var b strings.Builder
	b.WriteString("# generated by failover-backend - do not edit by hand\n")
	b.WriteString("# pulls these networks onto the tunnel so their traffic leaves\n")
	b.WriteString("# by the frontend's public address rather than the house's.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTEgressTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTEgressTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTEgressTable)

	b.WriteString("\tchain prerouting {\n")
	b.WriteString("\t\ttype filter hook prerouting priority mangle; policy accept;\n")
	for _, c := range cidrs {
		fmt.Fprintf(&b, "\t\tip saddr %s %s meta mark set %#x\n", c, internetOnly, EgressMark)
	}
	b.WriteString("\t}\n")

	// Ahead of Docker's masquerade at srcnat.
	b.WriteString("\tchain postrouting {\n")
	b.WriteString("\t\ttype nat hook postrouting priority -10; policy accept;\n")
	for _, c := range cidrs {
		fmt.Fprintf(&b, "\t\tip saddr %s oifname %s snat to %s\n", c, set(ifaces), overlayIP)
	}
	b.WriteString("\t}\n")

	b.WriteString("}\n")
	return b.String()
}

// EgressNetworks parses the networks an agent has been told to pull onto the
// overlay and re-renders them from what it parsed. Anything that is not an
// IPv4 network is dropped.
//
// The strings arrive over the control channel, and until this existed they
// went into the generated file unparsed and unquoted, straight into `nft -f`
// as root. web.validate checks them, but that runs on a different host at save
// time, which is the wrong place for this to be the only check: what reaches
// the file here is whatever the peer at the other end of a socket said, and a
// value carrying a newline is not one bad rule but a free hand with the whole
// ruleset - a chain of its own, a dnat, anything nft will load.
//
// Rendering the parsed form rather than passing the accepted string through is
// the half that makes it a boundary rather than a filter: there is then no path
// by which an unexamined byte reaches the file. It changes nothing for a
// configuration the portal accepted, because web.parseIPv4Network already
// normalises to exactly this, and sysx/nft_test.go pins that.
//
// Dropping a bad entry rather than refusing the batch is deliberate, and
// matches mergeCIDRs in protect.go: nft rejects a whole table over one bad
// element, and one unusable network must not take a working egress ruleset -
// or, on the backend, the reply path beside it - down with it.
func EgressNetworks(cidrs []string) []string {
	out := make([]string, 0, len(cidrs))
	for _, c := range cidrs {
		if n := NetworkLiteral(c); n != "" {
			out = append(out, n)
		}
	}
	return out
}

// NetworkLiteral returns an IPv4 network as nft should see it, or "" for
// anything that is not one. Host bits are masked off, so the string it returns
// is one nft will load: a value like 10.99.0.5/24 is rejected outright with
// "Address has host bits set", and it rejects the whole table with it.
//
// The single-network half of EgressNetworks, for the values that arrive one at
// a time rather than as a list - the overlay subnet in particular, which rides
// the same pushed control message as the networks and had been going into the
// generated rules with a bare %s. Filtering a list can drop a bad entry and
// keep the rest; a lone value has no such choice, so every caller has to treat
// "" as a failure rather than as a network.
func NetworkLiteral(cidr string) string {
	_, n, err := net.ParseCIDR(strings.TrimSpace(cidr))
	if err != nil || n.IP.To4() == nil {
		return ""
	}
	if _, bits := n.Mask.Size(); bits != 32 {
		return ""
	}
	return n.String()
}

// AddressLiteral returns an IPv4 address as nft should see it, or "" for
// anything that is not one.
//
// The companion to EgressNetworks, and it exists for the same reason: on the
// backend the overlay address beside those networks arrives over the control
// channel, in the pushed configuration, and was rendered into the file with
// %s. The networks were the loud version of that problem and this was the
// quiet one.
//
// A generator handed an address it cannot use renders nothing at all, and
// every caller has to treat that as a failure rather than as a ruleset. It is
// not self-announcing: an empty file is one `nft -f` accepts without complaint,
// so a caller that passes it on installs nothing and reports success.
func AddressLiteral(addr string) string {
	ip := net.ParseIP(strings.TrimSpace(addr))
	if ip == nil || ip.To4() == nil {
		return ""
	}
	return ip.To4().String()
}

// BuildReturnRuleset renders the backend's connection-marking ruleset.
//
// Only the reply direction restores the mark. Restoring it for every packet
// looks equivalent and is not: the request arriving from a tunnel would carry
// the mark through its own DNAT, so a packet destined for a container would be
// routed by the return table and sent straight back out the tunnel it came
// from. That was observed in production and it looks exactly like the service
// being down.
func BuildReturnRuleset(ifaces []string) string {
	var b strings.Builder
	b.WriteString("# generated by failover-backend - do not edit by hand\n")
	b.WriteString("# marks connections arriving from a tunnel so their replies\n")
	b.WriteString("# route back out one, even after a container DNAT has rewritten\n")
	b.WriteString("# their source address.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTReturnTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTReturnTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTReturnTable)
	b.WriteString("\tchain prerouting {\n")
	b.WriteString("\t\ttype filter hook prerouting priority mangle; policy accept;\n")

	if len(ifaces) > 0 {
		quoted := make([]string, 0, len(ifaces))
		for _, i := range ifaces {
			quoted = append(quoted, fmt.Sprintf("%q", i))
		}
		// `ct direction original` is load-bearing, not decoration. Without it
		// this also stamps connections the backend *started* down the tunnel -
		// the egress feature's traffic - because their replies arrive on a
		// tunnel too. Those would then have the return mark restored below,
		// get routed by table 100, and be sent straight back out the tunnel
		// instead of to the container that is waiting for them. Only a
		// connection whose first packet arrived from a tunnel is one whose
		// replies belong back down it.
		fmt.Fprintf(&b, "\t\tiifname { %s } ct direction original ct mark set %#x\n",
			strings.Join(quoted, ", "), ReturnMark)
	}
	fmt.Fprintf(&b, "\t\tct direction reply meta mark set ct mark\n")

	b.WriteString("\t}\n")
	// The backend's half of the clamp: a container's SYN on its way into the
	// tunnel, and a containerised server's SYN-ACK to a player. See
	// writeMSSClamp. A service on the host itself needs none of this.
	writeMSSClamp(&b, ifaces)
	b.WriteString("}\n")
	return b.String()
}

// ApplyRuleset writes the ruleset to disk and loads it atomically. The file is
// left in place on purpose: it is the readable record of what the agent
// published, and can be reloaded by hand with `nft -f`.
func ApplyRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "ruleset.nft"), ruleset)
}

// ApplyReturnRuleset loads the backend's marking ruleset.
func ApplyReturnRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "return.nft"), ruleset)
}

func applyRuleset(ctx context.Context, r Runner, path, ruleset string) (string, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("state dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(ruleset), 0o644); err != nil {
		return "", fmt.Errorf("write ruleset: %w", err)
	}
	if _, err := r.Run(ctx, "nft", "-f", path); err != nil {
		return path, fmt.Errorf("load ruleset: %w", err)
	}
	return path, nil
}

// RemoveRuleset deletes the agent's nftables table entirely.
func RemoveRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTTable)
}

// RemoveReturnRuleset deletes the backend's marking table.
func RemoveReturnRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTReturnTable)
}

// forwardComment tags every rule the agent inserts into a chain it does not
// own, so it can find them again to remove them.
const forwardComment = "failover"

// overlayForwardComment marks the exceptions a host needs when it *forwards*
// overlay traffic rather than terminating it - the backend, once there are
// linkers behind it. Distinct from the other two so each feature's rules can
// be found and removed on their own.
const overlayForwardComment = "failover_overlay"

// egressForwardComment marks the exception for backend-originated traffic, so
// that toggling that feature off leaves the published exceptions in place.
const egressForwardComment = "failover_egress"

// commentNeedle renders how nft prints a comment, so that searching for one
// cannot match another that merely starts with the same text - "failover" is a
// prefix of "failover_egress", and matching loosely would have the published
// exceptions and the egress one delete each other.
func commentNeedle(comment string) string { return `comment "` + comment + `"` }

// DockerUserChain is Docker's documented extension point: a chain jumped from
// FORWARD before its own rules, which Docker never flushes.
const DockerUserChain = "DOCKER-USER"

// EnsureForwardExceptions lets published traffic cross the frontend when
// something else owns a drop-policy forward chain.
//
// Docker sets the filter table's FORWARD policy to drop. Published traffic is
// DNAT'd and therefore forwarded, and nftables gives no way to override that
// from another table: an accept is only final for the chain it appears in,
// while a drop is final everywhere. The agent's own table cannot rescue the
// packet, so the exceptions have to go into the chain Docker leaves for
// exactly this purpose.
//
// Matching is by connection state plus destination, never by source address:
// a reply has its source rewritten back to the public address before the
// forward hook sees it, so a source match silently never fires.
//
// Does nothing when no such chain exists, which is the common case.
// The destination is the overlay data prefix rather than the backend's address
// alone, so a service published to a linker crosses the frontend on the same
// exception. Where no linkers are configured that prefix is the backend's /32
// and the rule is unchanged.
func EnsureForwardExceptions(ctx context.Context, r Runner, dataPrefix string) error {
	existing, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return nil // no Docker, nothing to work around
	}

	// Checked against the prefix, not merely against the comment. Skipping on
	// the comment alone meant the rule was written once and never revisited:
	// setting overlay.subnet later widened the route and the egress NAT but
	// left this accept pinned to the backend's /32, so a service published to
	// a linker was DNAT'd correctly and then dropped by the forward policy on
	// the way out. Nothing reported it - a drop is a timeout, which reads as
	// the far host being down.
	dropStaleForwardRules(ctx, r, existing, forwardComment, "daddr", dataPrefix)

	rules := [][]string{
		{"ip", "daddr", dataPrefix, "accept"},
		{"ct", "state", "established,related", "accept"},
	}
	for _, rule := range rules {
		if hasForwardRule(existing, forwardComment, rule) {
			continue
		}
		args := append([]string{"insert", "rule", "ip", "filter", DockerUserChain}, rule...)
		args = append(args, "comment", fmt.Sprintf("%q", forwardComment))
		if _, err := r.Run(ctx, "nft", args...); err != nil {
			return fmt.Errorf("insert forward exception: %w", err)
		}
	}
	return nil
}

// EnsureOverlayForwardExceptions lets overlay traffic cross a host that routes
// it onward, when something else owns a drop-policy forward chain.
//
// The backend terminated everything until linkers existed, so it never
// forwarded a packet and never needed this. With a linker behind it, every
// packet in both directions is forwarded: in on a tunnel and out to the LAN
// for published traffic, in on the LAN and out a tunnel for the linker's own
// control channel and egress. Docker sets the filter table's FORWARD policy to
// drop, and an accept in the agent's own table cannot rescue a packet another
// chain drops, so the exceptions go in the chain Docker leaves for the purpose.
//
// Both directions, unlike the frontend's, and that difference is the point: on
// the frontend a reply's source is rewritten back to the public address before
// the forward hook sees it, so a source match never fires. Nothing is
// translated here. The overlay address is on the packet in both directions,
// which is what makes matching it precise rather than broad - that range
// carries this system's traffic and nothing else.
//
// Does nothing when no such chain exists, which is the common case, and the
// caller does nothing at all unless linkers are configured.
func EnsureOverlayForwardExceptions(ctx context.Context, r Runner, overlayPrefix string) error {
	if overlayPrefix == "" {
		return nil
	}
	// Re-parsed and re-rendered, for the reason EgressNetworks exists: this
	// value arrives on the same pushed control message as the egress networks,
	// and it is not a shell argument that a separate argv element would make
	// safe - nft joins its own argv and re-lexes the result, so a space in here
	// is a new rule token and a semicolon is a new rule. The generators beside
	// it were given this treatment and this call was not.
	prefix := NetworkLiteral(overlayPrefix)
	if prefix == "" {
		return fmt.Errorf("overlay subnet %q is not an IPv4 network", overlayPrefix)
	}
	overlayPrefix = prefix
	existing, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return nil // no Docker, nothing to work around
	}

	// Against the prefix rather than the comment alone, for the reason the
	// frontend's does: a subnet set later widens this, and a rule pinned to the
	// old prefix would drop exactly the traffic the change was made to carry.
	dropStaleForwardRules(ctx, r, existing, overlayForwardComment, "daddr", overlayPrefix)
	dropStaleForwardRules(ctx, r, existing, overlayForwardComment, "saddr", overlayPrefix)

	rules := [][]string{
		{"ip", "daddr", overlayPrefix, "accept"},
		{"ip", "saddr", overlayPrefix, "accept"},
	}
	for _, rule := range rules {
		if hasForwardRule(existing, overlayForwardComment, rule) {
			continue
		}
		args := append([]string{"insert", "rule", "ip", "filter", DockerUserChain}, rule...)
		args = append(args, "comment", fmt.Sprintf("%q", overlayForwardComment))
		if _, err := r.Run(ctx, "nft", args...); err != nil {
			return fmt.Errorf("insert overlay forward exception: %w", err)
		}
	}
	return nil
}

// RemoveOverlayForwardExceptions withdraws them, by comment, leaving every
// other rule in a chain the agent does not own alone.
func RemoveOverlayForwardExceptions(ctx context.Context, r Runner) {
	removeCommentedForwardRules(ctx, r, overlayForwardComment)
}

// hasForwardRule reports whether a chain listing already carries this exact
// rule under our comment.
func hasForwardRule(listing, comment string, rule []string) bool {
	needle := strings.Join(rule, " ")
	for _, line := range strings.Split(listing, "\n") {
		if !strings.Contains(line, commentNeedle(comment)) {
			continue
		}
		if strings.Contains(line, needle) {
			return true
		}
	}
	return false
}

// dropStaleForwardRules removes rules of ours that match on the given address
// field with a prefix we no longer want.
//
// Deleting by handle rather than rewriting the chain, because DOCKER-USER is
// not ours: an operator's own rules live there too, and flushing it to reassert
// two of our own would take theirs with it.
func dropStaleForwardRules(ctx context.Context, r Runner, listing, comment, field, want string) {
	for _, line := range strings.Split(listing, "\n") {
		if !strings.Contains(line, commentNeedle(comment)) || !strings.Contains(line, " "+field+" ") {
			continue
		}
		if strings.Contains(line, " "+field+" "+want+" ") {
			continue // already the prefix we want
		}
		i := strings.LastIndex(line, "# handle ")
		if i < 0 {
			continue
		}
		handle := strings.TrimSpace(line[i+len("# handle "):])
		_, _ = r.Run(ctx, "nft", "delete", "rule", "ip", "filter", DockerUserChain, "handle", handle)
	}
}

// EnsureEgressForwardException lets a connection the backend originates cross
// the forward path.
//
// It is separate from EnsureForwardExceptions, and matches on source where that
// one deliberately does not, because it covers the opposite direction. Those
// rules cover traffic arriving for a published service, whose reply has its
// source rewritten back to the public address before the forward hook sees it,
// so a source match there would silently never fire. This is a connection going
// the other way: it is still carrying the overlay source address at the forward
// hook, and matches nothing the published rules cover - not `ip daddr backend`,
// because the destination is somewhere on the internet, and not `ct state
// established`, because it is the first packet of a new connection. Without it
// the source NAT is installed correctly and nothing ever reaches it.
//
// It carries its own comment so that toggling the feature off removes this and
// leaves the published exceptions alone.
func EnsureEgressForwardException(ctx context.Context, r Runner, dataPrefix string) error {
	existing, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return nil // no Docker, nothing to work around
	}
	// Same reconciliation as the published exceptions, for the same reason:
	// widening the overlay has to widen what may leave by it, or a linker's
	// outbound traffic is dropped where the backend's is allowed.
	dropStaleForwardRules(ctx, r, existing, egressForwardComment, "saddr", dataPrefix)
	if hasForwardRule(existing, egressForwardComment, []string{"ip", "saddr", dataPrefix, "accept"}) {
		return nil
	}
	args := []string{"insert", "rule", "ip", "filter", DockerUserChain,
		"ip", "saddr", dataPrefix, "accept",
		"comment", fmt.Sprintf("%q", egressForwardComment)}
	if _, err := r.Run(ctx, "nft", args...); err != nil {
		return fmt.Errorf("insert egress forward exception: %w", err)
	}
	return nil
}

// RemoveEgressForwardException deletes the rule EnsureEgressForwardException
// added, and only that one.
func RemoveEgressForwardException(ctx context.Context, r Runner) {
	removeCommentedForwardRules(ctx, r, egressForwardComment)
}

// RemoveForwardExceptions deletes only the rules the agent inserted, found by
// their comment. Everything else in the chain belongs to somebody else.
func RemoveForwardExceptions(ctx context.Context, r Runner) {
	removeCommentedForwardRules(ctx, r, forwardComment)
}

// removeCommentedForwardRules deletes every rule in the chain carrying one
// comment, by handle. The comment is the only thing distinguishing the agent's
// rules from everyone else's in a chain it does not own.
func removeCommentedForwardRules(ctx context.Context, r Runner, comment string) {
	out, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return
	}
	for _, line := range strings.Split(out, "\n") {
		if !strings.Contains(line, commentNeedle(comment)) {
			continue
		}
		i := strings.LastIndex(line, "# handle ")
		if i < 0 {
			continue
		}
		handle := strings.TrimSpace(line[i+len("# handle "):])
		_, _ = r.Run(ctx, "nft", "delete", "rule", "ip", "filter", DockerUserChain, "handle", handle)
	}
}

// ForwardIsBlocked reports whether some chain the agent does not own drops
// forwarded traffic by default, which silently breaks every published service.
func ForwardIsBlocked(ctx context.Context, r Runner) bool {
	out, err := r.Run(ctx, "nft", "list", "ruleset")
	if err != nil {
		return false
	}
	for _, line := range strings.Split(out, "\n") {
		if strings.Contains(line, "hook forward") && strings.Contains(line, "policy drop") {
			return true
		}
	}
	return false
}
