package sysx

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/quinlan102/homeport/internal/model"
)

// NFTTable is the dedicated table the agent owns. Nothing else is touched, so
// removing every trace of this program is one command:
//
//	nft delete table ip failover
const NFTTable = "failover"

// NFTReturnTable is the backend's table. It carries no NAT of its own - only
// the connection marking that lets reply traffic find its way back out the
// tunnel it arrived on.
const NFTReturnTable = "failover_return"

// NFTEgressTable is the frontend's optional source-NAT table.
//
// It is a table of its own rather than a chain in NFTTable, and that separation
// is the point. NFTTable carries the published services and must never contain
// a masquerade - rewriting the source there would take the real client IP away
// from srcds and the web server, which is the reason the whole system routes
// instead of proxying, and `nft_test.go` asserts it. This table rewrites the
// source of traffic travelling the other way: connections the *backend*
// originates, where there is no client address to preserve because there is no
// client. Keeping them apart means the assertion on the published ruleset stays
// literally true, and this table can be added and removed on its own.
const NFTEgressTable = "failover_egress"

// ReturnMark stamps connections that arrived through a tunnel.
//
// The backend already routes replies by source address (ip rule from the
// overlay address), which is enough while the service listens on the host. It
// stops working the moment anything DNATs further - a container on a bridge
// network being the ordinary case - because the routing decision for the reply
// happens *before* its source is rewritten back to the overlay address. At that
// moment the packet still carries the container's address, matches no rule, and
// leaves by the default route instead of the tunnel.
//
// Marking the connection on the way in and restoring that mark on the way out
// routes by connection rather than by address, which survives any number of
// translations. 0x200 is clear of the path marks (0x101-0x103) and the control
// mark (0x100).
const ReturnMark = 0x200

// BuildRuleset renders the DNAT ruleset for the published services.
//
// Destination NAT only. There is deliberately no masquerade rule: leaving the
// source address alone is what makes the backend see the real client IP, for
// UDP as well as TCP, without any proxy in the path.
func BuildRuleset(cfg model.Config) string {
	var b strings.Builder
	b.WriteString("# generated by failover-frontend - do not edit by hand\n")
	b.WriteString("# destination NAT only; source addresses are never rewritten,\n")
	b.WriteString("# so srcds and the web server see real client IPs.\n\n")

	// Atomic replace: create-if-missing, delete, redefine.
	fmt.Fprintf(&b, "table ip %s\n", NFTTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTTable)
	b.WriteString("\tchain prerouting {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")

	for _, s := range cfg.Services {
		if !s.Enabled {
			continue
		}
		proto := strings.ToLower(s.Proto)
		if proto != "tcp" && proto != "udp" {
			continue
		}
		port := fmt.Sprintf("%d", s.Port)
		if s.PortEnd > s.Port {
			port = fmt.Sprintf("%d-%d", s.Port, s.PortEnd)
		}
		var rule strings.Builder
		rule.WriteString("\t\t")
		if cfg.Frontend.PublicIface != "" {
			fmt.Fprintf(&rule, "iifname %q ", cfg.Frontend.PublicIface)
		}
		if cfg.Frontend.PublicIP != "" {
			fmt.Fprintf(&rule, "ip daddr %s ", cfg.Frontend.PublicIP)
		}
		// Almost always the backend. A service names a different overlay
		// address only where a linker agent publishes it from another host,
		// and the routing to get there is the same route widened by one
		// prefix - there is no second mechanism here.
		fmt.Fprintf(&rule, "%s dport %s dnat to %s comment %q\n",
			proto, port, s.TargetOr(cfg.Overlay.BackendIP), s.Name)
		b.WriteString(rule.String())
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// BuildEgressRuleset renders the frontend's source-NAT for backend-originated
// traffic, or "" when the feature is off.
//
// The match is narrow on purpose: the overlay source address, and the public
// interface as the way out. Only the backend can send from the overlay address,
// and restricting the output interface keeps it away from anything heading back
// down a tunnel - masquerading there would rewrite the source of a reply to a
// player, which is exactly what the rest of the design exists to avoid.
//
// A configured public IP produces an snat rather than a masquerade: it is one
// less address lookup per connection, and it fails visibly if the address is
// wrong instead of silently picking a different one.
func BuildEgressRuleset(cfg model.Config) string {
	if !cfg.Frontend.BackendEgress || cfg.Overlay.BackendIP == "" || cfg.Frontend.PublicIface == "" {
		return ""
	}
	var b strings.Builder
	b.WriteString("# generated by failover-frontend - do not edit by hand\n")
	b.WriteString("# gives traffic the backend originates the frontend's public\n")
	b.WriteString("# address, so a game server is listed at the published address\n")
	b.WriteString("# rather than at the house's own internet service.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTEgressTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTEgressTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTEgressTable)
	b.WriteString("\tchain postrouting {\n")
	b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")

	// The whole overlay range, so a linker's traffic is translated by the same
	// rule as the backend's. On a site with no linkers MatchPrefix is the
	// backend's own address and this renders exactly as it always did.
	fmt.Fprintf(&b, "\t\tip saddr %s oifname %q ", cfg.Overlay.MatchPrefix(), cfg.Frontend.PublicIface)
	if cfg.Frontend.PublicIP != "" {
		fmt.Fprintf(&b, "snat to %s\n", cfg.Frontend.PublicIP)
	} else {
		b.WriteString("masquerade\n")
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// ApplyEgressRuleset loads the frontend's source-NAT table.
func ApplyEgressRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "egress.nft"), ruleset)
}

// RemoveEgressRuleset deletes the frontend's source-NAT table.
func RemoveEgressRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTEgressTable)
}

// EgressMark stamps traffic being pulled onto the tunnel from a backend-side
// network. Clear of the path marks (0x101-0x103), the control mark (0x100) and
// the return mark (0x200).
const EgressMark = 0x300

// BuildBackendEgressRuleset renders the backend half of the egress feature, or
// "" when no source networks are configured.
//
// Two rules, doing two different jobs:
//
// The prerouting mark is what redirects the traffic. A container's packets
// arrive at the host over its bridge and are forwarded, so the routing decision
// for them happens after this hook - setting the mark here is what makes
// `ip rule fwmark 0x300 lookup 100` send them down the active tunnel instead of
// out to pfSense. Table 100 is the return table, which already tracks the
// frontend's choice, so this follows failover with nothing extra to maintain.
//
// The postrouting SNAT rewrites the source to the overlay address, because that
// is what the frontend's own egress rule matches and what it can route a reply
// back to. Without it the packet arrives at the frontend carrying a private
// container address that nothing downstream knows how to answer.
//
// The SNAT priority is deliberately ahead of srcnat (100), which is where
// Docker installs its own masquerade. Left to run first, Docker would rewrite
// the source to an address on the output interface - and the tunnels carry no
// address at all, because wg-quick runs with Table = off and no Address.
func BuildBackendEgressRuleset(cidrs, ifaces []string, overlayIP string) string {
	if len(cidrs) == 0 || len(ifaces) == 0 || overlayIP == "" {
		return ""
	}
	set := func(items []string) string {
		quoted := make([]string, 0, len(items))
		for _, i := range items {
			quoted = append(quoted, fmt.Sprintf("%q", i))
		}
		return "{ " + strings.Join(quoted, ", ") + " }"
	}

	var b strings.Builder
	b.WriteString("# generated by failover-backend - do not edit by hand\n")
	b.WriteString("# pulls these networks onto the tunnel so their traffic leaves\n")
	b.WriteString("# by the frontend's public address rather than the house's.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTEgressTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTEgressTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTEgressTable)

	b.WriteString("\tchain prerouting {\n")
	b.WriteString("\t\ttype filter hook prerouting priority mangle; policy accept;\n")
	for _, c := range cidrs {
		fmt.Fprintf(&b, "\t\tip saddr %s meta mark set %#x\n", c, EgressMark)
	}
	b.WriteString("\t}\n")

	// Ahead of Docker's masquerade at srcnat.
	b.WriteString("\tchain postrouting {\n")
	b.WriteString("\t\ttype nat hook postrouting priority -10; policy accept;\n")
	for _, c := range cidrs {
		fmt.Fprintf(&b, "\t\tip saddr %s oifname %s snat to %s\n", c, set(ifaces), overlayIP)
	}
	b.WriteString("\t}\n")

	b.WriteString("}\n")
	return b.String()
}

// BuildReturnRuleset renders the backend's connection-marking ruleset.
//
// Only the reply direction restores the mark. Restoring it for every packet
// looks equivalent and is not: the request arriving from a tunnel would carry
// the mark through its own DNAT, so a packet destined for a container would be
// routed by the return table and sent straight back out the tunnel it came
// from. That was observed in production and it looks exactly like the service
// being down.
func BuildReturnRuleset(ifaces []string) string {
	var b strings.Builder
	b.WriteString("# generated by failover-backend - do not edit by hand\n")
	b.WriteString("# marks connections arriving from a tunnel so their replies\n")
	b.WriteString("# route back out one, even after a container DNAT has rewritten\n")
	b.WriteString("# their source address.\n\n")

	fmt.Fprintf(&b, "table ip %s\n", NFTReturnTable)
	fmt.Fprintf(&b, "delete table ip %s\n\n", NFTReturnTable)
	fmt.Fprintf(&b, "table ip %s {\n", NFTReturnTable)
	b.WriteString("\tchain prerouting {\n")
	b.WriteString("\t\ttype filter hook prerouting priority mangle; policy accept;\n")

	if len(ifaces) > 0 {
		quoted := make([]string, 0, len(ifaces))
		for _, i := range ifaces {
			quoted = append(quoted, fmt.Sprintf("%q", i))
		}
		// `ct direction original` is load-bearing, not decoration. Without it
		// this also stamps connections the backend *started* down the tunnel -
		// the egress feature's traffic - because their replies arrive on a
		// tunnel too. Those would then have the return mark restored below,
		// get routed by table 100, and be sent straight back out the tunnel
		// instead of to the container that is waiting for them. Only a
		// connection whose first packet arrived from a tunnel is one whose
		// replies belong back down it.
		fmt.Fprintf(&b, "\t\tiifname { %s } ct direction original ct mark set %#x\n",
			strings.Join(quoted, ", "), ReturnMark)
	}
	fmt.Fprintf(&b, "\t\tct direction reply meta mark set ct mark\n")

	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// ApplyRuleset writes the ruleset to disk and loads it atomically. The file is
// left in place on purpose: it is the readable record of what the agent
// published, and can be reloaded by hand with `nft -f`.
func ApplyRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "ruleset.nft"), ruleset)
}

// ApplyReturnRuleset loads the backend's marking ruleset.
func ApplyReturnRuleset(ctx context.Context, r Runner, stateDir, ruleset string) (string, error) {
	return applyRuleset(ctx, r, filepath.Join(stateDir, "return.nft"), ruleset)
}

func applyRuleset(ctx context.Context, r Runner, path, ruleset string) (string, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("state dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(ruleset), 0o644); err != nil {
		return "", fmt.Errorf("write ruleset: %w", err)
	}
	if _, err := r.Run(ctx, "nft", "-f", path); err != nil {
		return path, fmt.Errorf("load ruleset: %w", err)
	}
	return path, nil
}

// RemoveRuleset deletes the agent's nftables table entirely.
func RemoveRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTTable)
}

// RemoveReturnRuleset deletes the backend's marking table.
func RemoveReturnRuleset(ctx context.Context, r Runner) {
	_, _ = r.Run(ctx, "nft", "delete", "table", "ip", NFTReturnTable)
}

// forwardComment tags every rule the agent inserts into a chain it does not
// own, so it can find them again to remove them.
const forwardComment = "failover"

// egressForwardComment marks the exception for backend-originated traffic, so
// that toggling that feature off leaves the published exceptions in place.
const egressForwardComment = "failover_egress"

// commentNeedle renders how nft prints a comment, so that searching for one
// cannot match another that merely starts with the same text - "failover" is a
// prefix of "failover_egress", and matching loosely would have the published
// exceptions and the egress one delete each other.
func commentNeedle(comment string) string { return `comment "` + comment + `"` }

// DockerUserChain is Docker's documented extension point: a chain jumped from
// FORWARD before its own rules, which Docker never flushes.
const DockerUserChain = "DOCKER-USER"

// EnsureForwardExceptions lets published traffic cross the frontend when
// something else owns a drop-policy forward chain.
//
// Docker sets the filter table's FORWARD policy to drop. Published traffic is
// DNAT'd and therefore forwarded, and nftables gives no way to override that
// from another table: an accept is only final for the chain it appears in,
// while a drop is final everywhere. The agent's own table cannot rescue the
// packet, so the exceptions have to go into the chain Docker leaves for
// exactly this purpose.
//
// Matching is by connection state plus destination, never by source address:
// a reply has its source rewritten back to the public address before the
// forward hook sees it, so a source match silently never fires.
//
// Does nothing when no such chain exists, which is the common case.
// The destination is the overlay data prefix rather than the backend's address
// alone, so a service published to a linker crosses the frontend on the same
// exception. Where no linkers are configured that prefix is the backend's /32
// and the rule is unchanged.
func EnsureForwardExceptions(ctx context.Context, r Runner, dataPrefix string) error {
	existing, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return nil // no Docker, nothing to work around
	}

	// Checked against the prefix, not merely against the comment. Skipping on
	// the comment alone meant the rule was written once and never revisited:
	// setting overlay.subnet later widened the route and the egress NAT but
	// left this accept pinned to the backend's /32, so a service published to
	// a linker was DNAT'd correctly and then dropped by the forward policy on
	// the way out. Nothing reported it - a drop is a timeout, which reads as
	// the far host being down.
	dropStaleForwardRules(ctx, r, existing, forwardComment, "daddr", dataPrefix)

	rules := [][]string{
		{"ip", "daddr", dataPrefix, "accept"},
		{"ct", "state", "established,related", "accept"},
	}
	for _, rule := range rules {
		if hasForwardRule(existing, forwardComment, rule) {
			continue
		}
		args := append([]string{"insert", "rule", "ip", "filter", DockerUserChain}, rule...)
		args = append(args, "comment", fmt.Sprintf("%q", forwardComment))
		if _, err := r.Run(ctx, "nft", args...); err != nil {
			return fmt.Errorf("insert forward exception: %w", err)
		}
	}
	return nil
}

// hasForwardRule reports whether a chain listing already carries this exact
// rule under our comment.
func hasForwardRule(listing, comment string, rule []string) bool {
	needle := strings.Join(rule, " ")
	for _, line := range strings.Split(listing, "\n") {
		if !strings.Contains(line, commentNeedle(comment)) {
			continue
		}
		if strings.Contains(line, needle) {
			return true
		}
	}
	return false
}

// dropStaleForwardRules removes rules of ours that match on the given address
// field with a prefix we no longer want.
//
// Deleting by handle rather than rewriting the chain, because DOCKER-USER is
// not ours: an operator's own rules live there too, and flushing it to reassert
// two of our own would take theirs with it.
func dropStaleForwardRules(ctx context.Context, r Runner, listing, comment, field, want string) {
	for _, line := range strings.Split(listing, "\n") {
		if !strings.Contains(line, commentNeedle(comment)) || !strings.Contains(line, " "+field+" ") {
			continue
		}
		if strings.Contains(line, " "+field+" "+want+" ") {
			continue // already the prefix we want
		}
		i := strings.LastIndex(line, "# handle ")
		if i < 0 {
			continue
		}
		handle := strings.TrimSpace(line[i+len("# handle "):])
		_, _ = r.Run(ctx, "nft", "delete", "rule", "ip", "filter", DockerUserChain, "handle", handle)
	}
}

// EnsureEgressForwardException lets a connection the backend originates cross
// the forward path.
//
// It is separate from EnsureForwardExceptions, and matches on source where that
// one deliberately does not, because it covers the opposite direction. Those
// rules cover traffic arriving for a published service, whose reply has its
// source rewritten back to the public address before the forward hook sees it,
// so a source match there would silently never fire. This is a connection going
// the other way: it is still carrying the overlay source address at the forward
// hook, and matches nothing the published rules cover - not `ip daddr backend`,
// because the destination is somewhere on the internet, and not `ct state
// established`, because it is the first packet of a new connection. Without it
// the source NAT is installed correctly and nothing ever reaches it.
//
// It carries its own comment so that toggling the feature off removes this and
// leaves the published exceptions alone.
func EnsureEgressForwardException(ctx context.Context, r Runner, dataPrefix string) error {
	existing, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return nil // no Docker, nothing to work around
	}
	// Same reconciliation as the published exceptions, for the same reason:
	// widening the overlay has to widen what may leave by it, or a linker's
	// outbound traffic is dropped where the backend's is allowed.
	dropStaleForwardRules(ctx, r, existing, egressForwardComment, "saddr", dataPrefix)
	if hasForwardRule(existing, egressForwardComment, []string{"ip", "saddr", dataPrefix, "accept"}) {
		return nil
	}
	args := []string{"insert", "rule", "ip", "filter", DockerUserChain,
		"ip", "saddr", dataPrefix, "accept",
		"comment", fmt.Sprintf("%q", egressForwardComment)}
	if _, err := r.Run(ctx, "nft", args...); err != nil {
		return fmt.Errorf("insert egress forward exception: %w", err)
	}
	return nil
}

// RemoveEgressForwardException deletes the rule EnsureEgressForwardException
// added, and only that one.
func RemoveEgressForwardException(ctx context.Context, r Runner) {
	removeCommentedForwardRules(ctx, r, egressForwardComment)
}

// RemoveForwardExceptions deletes only the rules the agent inserted, found by
// their comment. Everything else in the chain belongs to somebody else.
func RemoveForwardExceptions(ctx context.Context, r Runner) {
	removeCommentedForwardRules(ctx, r, forwardComment)
}

// removeCommentedForwardRules deletes every rule in the chain carrying one
// comment, by handle. The comment is the only thing distinguishing the agent's
// rules from everyone else's in a chain it does not own.
func removeCommentedForwardRules(ctx context.Context, r Runner, comment string) {
	out, err := r.Run(ctx, "nft", "-a", "list", "chain", "ip", "filter", DockerUserChain)
	if err != nil {
		return
	}
	for _, line := range strings.Split(out, "\n") {
		if !strings.Contains(line, commentNeedle(comment)) {
			continue
		}
		i := strings.LastIndex(line, "# handle ")
		if i < 0 {
			continue
		}
		handle := strings.TrimSpace(line[i+len("# handle "):])
		_, _ = r.Run(ctx, "nft", "delete", "rule", "ip", "filter", DockerUserChain, "handle", handle)
	}
}

// ForwardIsBlocked reports whether some chain the agent does not own drops
// forwarded traffic by default, which silently breaks every published service.
func ForwardIsBlocked(ctx context.Context, r Runner) bool {
	out, err := r.Run(ctx, "nft", "list", "ruleset")
	if err != nil {
		return false
	}
	for _, line := range strings.Split(out, "\n") {
		if strings.Contains(line, "hook forward") && strings.Contains(line, "policy drop") {
			return true
		}
	}
	return false
}
